### ISSUE TITLE
Telegram Bot Issue

### ISSUE THREAD

**Issue by teguhraharjo17** [eusonlito/GPS-Tracker#85] opened 2024-11-14 02:03 UTC
**Why can't the telegram bot that I have added receive data? I have set everything up, and also I have done php artisan optimize previously**

![Telegram Bot(2)](https://github.com/user-attachments/assets/ec4f6414-afdc-4e92-b535-99bc47330cf7)
![Telegram Bot(3)](https://github.com/user-attachments/assets/fb0781c0-93ba-4f38-bdc1-687ff2db414f)
![Telegram Bot](https://github.com/user-attachments/assets/181f18a0-00b2-4c0b-b5f8-2265dd104adb)

**Comment by eusonlito** [comment] 2024-11-14 12:37
There are some error at logs? Do you have some alarm enabled with telegram?

**Comment by teguhraharjo17** [comment] 2024-11-14 12:57
![image](https://github.com/user-attachments/assets/1af351c3-f069-438a-acd7-a38f83a37cc5)

yes, i have alarm enabled with telegram and there is no error at logs

**Comment by eusonlito** [comment] 2024-11-14 13:17
But there aren't notifications.

**Comment by teguhraharjo17** [comment] 2024-11-15 02:27
That's why I'm confused why there is no notification, is my setting that I have screenshot correct, where is the mistake?

**Comment by eusonlito** [comment] 2024-11-15 07:49
It seems that the alarm has been set up correctly, but no movement has been detected yet, so the corresponding notification hasn’t been triggered. Is that correct?

**Comment by eusonlito** [comment] 2024-11-15 15:39
If you want, please send me your platform details at lito <at> eordes <dot> com

**Comment by teguhraharjo17** [comment] 2024-11-16 07:43
for my telegram bot name or link is https://t.me/track_car_bot, and for the HTTP API is 7781726791:AAE4ntJhBlh6v_7reJZThjMYe3iphPtpdV4

**Comment by eusonlito** [comment] 2024-11-16 13:31
@teguhraharjo17 do not publish your telegram key or could be used by any other user 😅

I think the problem is not about telegram notification, but movement alarm.

I will add a telegram connection test button to verify integration.

**Comment by eusonlito** [comment] 2024-11-16 23:03
Added Telegram Test message from profile.

Update your environment with `./composer deploy` and test the connection.

**Comment by teguhraharjo17** [comment] 2024-11-20 02:02
![Gambar WhatsApp 2024-11-20 pukul 09 00 32_4c32fbe4](https://github.com/user-attachments/assets/aa1a1e33-5400-41ef-b216-24e38f24ff24)

the connection test to the telegram was successful

**Comment by teguhraharjo17** [comment] 2024-11-20 07:47
![Gambar WhatsApp 2024-11-20 pukul 14 44 44_b7eb1f61](https://github.com/user-attachments/assets/cb914d06-2161-451a-a8c4-05fad7d0bd4e)

I checked the queue by doing php artisan queue:work and saw that the checkposition failed or did not work.

**Comment by eusonlito** [comment] 2024-11-20 07:50
And the Laravel log?

**Comment by teguhraharjo17** [comment] 2024-11-20 08:15
![image](https://github.com/user-attachments/assets/6ee26e6b-9674-4cba-9597-811ad4b9234b)
![image](https://github.com/user-attachments/assets/ef7140c1-bacf-4502-a7f6-83f2fb1d48d3)


iam sorry the queue for checkposition is work and the data in notification is already in, but in telegram is didnt sent successfully, so the problem is in telegram connection? but the test connection is succes too

**Comment by eusonlito** [comment] 2024-11-20 08:24
And laravel log? Monitor > Logs > laravel

**Comment by teguhraharjo17** [comment] 2024-11-20 08:40
i add some log info in my CheckPosition(job) and action like this

![image](https://github.com/user-attachments/assets/8015ae32-65a0-4c47-b4f1-ed613c7e55dd)

**Comment by eusonlito** [comment] 2024-11-20 08:42
You need to close each notification so the system can resend alerts via Telegram. Otherwise, it will keep sending notifications repeatedly for events like motion or geofence.

**Comment by eusonlito** [comment] 2024-11-20 09:24
You can try:

1. Close all alarm notifications
2. Trigger an alarm
3. Check notification created
4. Check Laravel log

**Comment by eusonlito** [comment] 2024-11-22 01:33
You should setup the queue with a cron or managed by supervisor: https://github.com/eusonlito/GPS-Tracker/wiki/%5BEN%5D-Local-Installation

Check point 7.

**Comment by teguhraharjo17** [comment] 2024-11-22 02:03
I have set it up, I set the cron in the www-data user.

![Gambar WhatsApp 2024-11-22 pukul 09 01 30_e066595b](https://github.com/user-attachments/assets/8fa49984-3a1c-4543-a3b8-6cdb33aaf8b2)

**Comment by teguhraharjo17** [comment] 2024-11-22 10:49
![image](https://github.com/user-attachments/assets/e54793ae-2968-4fd4-a0ba-82dff8abe67e)

i dont have that file in artisan, how can i get it?

**Comment by eusonlito** [comment] 2024-11-22 10:53
check date nested subfolders > `2024/11/22/schedule-run.log`

**Comment by teguhraharjo17** [comment] 2024-11-22 10:57
![image](https://github.com/user-attachments/assets/13d8149d-933e-4218-95f0-23d52b9a0918)

just have this in 2024/11

**Comment by eusonlito** [comment] 2024-11-22 11:12
then your cronjob is not working...

Set a simple version with:

```
* * * * * /usr/bin/php /var/www/html/tracker/artisan schedule:run >> /var/www/html/tracker/storage/logs/artisan-schedule-run.log 2>&1
```

**Comment by eusonlito** [comment] 2024-11-28 20:16
Can we close the issue?

**Closed** 2024-12-12 00:36 UTC
